from pathlib import Path
path = Path('src/MyApp.tsx')
text = path.read_text(encoding='utf-8')
old = "              <div className=\"mt-4\\">\\n                <div className=\"flex items-center justify-between text-[11px] font-medium text-slate-500\\">\\n                  <span>MST time slots</span>\\n                  <span>{slotsUsed}/{MST_SLOT_TOTAL}{overflowSlots > 0 ?  (+ overflow) : ''}</span>\\n                </div>\\n                <div className=\"overflow-x-auto\\">\\n                  <div className=\"flex min-w-[512px] gap-1 py-1\\">\\n                    {mstSlots.map((slotOwner, index) => {\\n                      const color = slotOwner !== null ? TIMING_COLORS[slotOwner % TIMING_COLORS.length] : '#cbd5f5';\\n                      const tooltip = slotOwner !== null\\n                        ? ${parsed[slotOwner]?.label ?? 'Timing'} •  slots •  Gbps\\n                        : 'Unallocated slot';\\n                      return (\\n                        <div\\n                          key={index}\\n                          className=\"h-3 w-3 rounded-sm border border-slate-200\\"\\n                          style={{ backgroundColor: color, opacity: slotOwner !== null ? 1 : 0.35 }}\\n                          title={tooltip}\\n                        />\\n                      );\\n                    })}\\n                  </div>\\n                </div>\\n              </div>\\n"
if old not in text:
    raise SystemExit('old MST block not found')
new = "              <div className=\"mt-4\">\n                <div className=\"flex items-center justify-between text-[11px] font-medium text-slate-500\">\n                  <span>MST time slots</span>\n                  <span>{slotsUsed}/{MST_SLOT_TOTAL}{overflowSlots > 0 ?  (+ overflow) : ''}</span>\n                </div>\n                <div className=\"mt-2\">\n                  <div\n                    className=\"grid gap-[2px]\"\n                    style={{ gridTemplateColumns: epeat(, minmax(0, 1fr)) }}\n                  >\n                    {mstSlots.map((slotOwner, index) => {\n                      const color = slotOwner !== null ? TIMING_COLORS[slotOwner % TIMING_COLORS.length] : '#cbd5f5';\n                      const tooltip = slotOwner !== null\n                        ? ${parsed[slotOwner]?.label ?? 'Timing'} •  slots •  Gbps\n                        : 'Unallocated slot';\n                      return (\n                        <div\n                          key={index}\n                          className=\"h-3 rounded-sm border border-slate-200\"\n                          style={{ backgroundColor: color, opacity: slotOwner !== null ? 1 : 0.35 }}\n                          title={tooltip}\n                        />\n                      );\n                    })}\n                  </div>\n                </div>\n              </div>\n"
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
